dark-mode: true
auto-commits: false
watch-files: true
read:
  - CONVENTIONS.md
model: gemini/gemini-2.5-pro-preview-03-25
lint: false
test: false
lint-cmd: "pnpm check"
test-cmd: "pnpm test"
auto-test: true
notifications: true
code-theme: "gruvbox-dark"
