# fly.toml app configuration file generated for miniastro on 2025-04-29T13:28:04+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'miniastro'
primary_region = 'iad'

[build]

[deploy]
  strategy = 'rolling'

[[mounts]]
  source = 'data'
  destination = '/data'

[http_service]
  internal_port = 4321
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = false
  min_machines_running = 1
  max_machines_running = 1
  processes = ['app']

  [[http_service.checks]]
    interval = '5s'
    timeout = '2s'
    grace_period = '10s'
    method = 'GET'
    path = '/health'
    protocol = 'http'

[[vm]]
  memory = '1024mb'
  cpu_kind = 'shared'
  cpus = 1
